import React from 'react';
import Navbar from '../components/Navbar';
import Head from 'next/head';


export default function about() {
  return (
    <div className=''>
      <Navbar />
      <Head>
        <title>Content Connector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="" href="" />
      </Head>
      <h2 className="grid items-center">Who we are</h2>
      <p className="grid items-center">
        We are a web application that allows local freelancers to connect with
        small businesses, giving businesses a platform to express their business
        needs and create a relationship through communication.
      </p>
    </div>
  );
}
