import React from 'react';
import Navbar from '../components/Navbar';
import Head from 'next/head';


export default function messages() {
  return (
    <div>
      <Navbar />
      <Head>
        <title>Content Connector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="" href="" />
      </Head>
      <main>
        User messages - "pages/messages.js"
      </main>
    </div>
  );
}
